### PR TITLE
copy

### PR DESCRIPTION
**Pull request by ksunden**
Still a little buggy, especially when trying to use relative paths

### CODE REVIEW

**Comment by ksunden** [comment]
currently getting the following error message:

```[test.h5: 2D/] > cp ../1D/T d1
cp: overwrite 'd1'? y
Traceback (most recent call last):
  File "/home/kyle/github/h5cli/src/h5cli/cli.py", line 109, in do_cp
    self.explorer.group('.').copy(src, dest)
  File "/usr/lib/python3.6/site-packages/h5py/_hl/group.py", line 399, in copy
    copypl, base.dlcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 217, in h5py.h5o.copy
ValueError: Destination object already exists (destination object already exists)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cmd2.py", line 981, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/usr/lib/python3.6/site-packages/cmd2.py", line 1179, in onecmd
    stop = func(statement)
  File "/usr/lib/python3.6/site-packages/cmd2.py", line 432, in new_func
    result = func(instance, arg, opts)
  File "/home/kyle/github/h5cli/src/h5cli/cli.py", line 120, in do_cp
    self.explorer.group('.').copy(src, dest)
  File "/usr/lib/python3.6/site-packages/h5py/_hl/group.py", line 399, in copy
    copypl, base.dlcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 217, in h5py.h5o.copy
KeyError: "Source object not found (object 'd1' doesn't exist)"
```

Note `d1` initially exists in the file, but the interaction which says `y` asks it to remove and try again.
The object is successfully removed, but not then successfully copied.

Oddly, it's complaining that the 'Source object' is not found, but gives the name which should be the destination.

**Comment by ksunden** [comment]
As an aside, I look forward to having proper unit tests on this function. I do not at all look forward to writing them, though.

**Comment by ksunden** [comment]
I think I solved the above error, but still need to test this before merging.

Should be testable by others if there is interest (@untzag?)

Warning: Please make sure you are not acting on a file you would be sad if something got deleted in. This code has not been thoroughly tested, and can overwrite parts of the file

**Comment by untzag** [comment]
sorry to say that I'm getting the same error

I'm trying to copy a Group, though---is that allowed?

**Comment by ksunden** [comment]
Copying a group should work, note that you need to specify `-r` to copy a group, however

**Comment by ksunden** [comment]
I think the above error was because write permissions were not on the file, I merged back from master to give `sudo` so that it can be added

**Comment by ksunden** [comment]
Please ignore appveyor, that was set up when I was troubleshooting for another repo, it doesn't actually have anything to run yet. The web hook has been removed now

**Review by lphk92 — APPROVED** [review]

**Pull request merged**
